openapi: 3.0.0
info:
  title: jira
  version: '1.0'
  contact:
    name: Wen-Zhe Liu
    email: liuwenzhe2008@qq.com
servers:
  - url: 'https://gapi-xxxxxx/jira'
    description: 刘文哲
paths:
  /user:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
                  id:
                    type:
                      - string
                      - number
                  xxx:
                    type: array
                    items: {}
              examples:
                '{ddddjfjdjfda|dfdd': {}
      operationId: get-user
      description: frdddsss
    post:
      summary: ''
      operationId: post-user
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  '':
                    type: string
components:
  schemas: {}
